apiRules:
  - exclude:
      uidRegex: ^NAudio
      type: Namespace
  - exclude:
      uidRegex: ^Noesis
      type: Namespace
  - exclude:
      uidRegex: ^OpenTK
      type: Namespace
  - exclude:
      uidRegex: ^System\.Windows
      type: Namespace
  - exclude:
      uidRegex: ^Valve
      type: Namespace
  - exclude:
      uidRegex: ^VuforiaSharp
      type: Namespace
  - exclude:
      uidRegex: ^EvergineStudio
      type: Namespace
  - exclude:
      uidRegex: ^WaveTestCore
      type: Namespace
