### YamlMime:ManagedReference
items:
- uid: WaveEngine.Framework.Models.Settings
  commentId: N:WaveEngine.Framework.Models.Settings
  id: WaveEngine.Framework.Models.Settings
  children:
  - WaveEngine.Framework.Models.Settings.ASettings
  - WaveEngine.Framework.Models.Settings.GameSettings
  - WaveEngine.Framework.Models.Settings.ISettingCategory
  - WaveEngine.Framework.Models.Settings.ProjectSettings
  - WaveEngine.Framework.Models.Settings.SceneSettings
  langs:
  - csharp
  - vb
  name: WaveEngine.Framework.Models.Settings
  nameWithType: WaveEngine.Framework.Models.Settings
  fullName: WaveEngine.Framework.Models.Settings
  type: Namespace
  assemblies:
  - WaveEngine.Framework
references:
- uid: WaveEngine.Framework.Models.Settings.ISettingCategory
  commentId: T:WaveEngine.Framework.Models.Settings.ISettingCategory
  parent: WaveEngine.Framework.Models.Settings
  name: ISettingCategory
  nameWithType: ISettingCategory
  fullName: WaveEngine.Framework.Models.Settings.ISettingCategory
- uid: WaveEngine.Framework.Models.Settings.GameSettings
  commentId: T:WaveEngine.Framework.Models.Settings.GameSettings
  parent: WaveEngine.Framework.Models.Settings
  name: GameSettings
  nameWithType: GameSettings
  fullName: WaveEngine.Framework.Models.Settings.GameSettings
- uid: WaveEngine.Framework.Models.Settings.ProjectSettings
  commentId: T:WaveEngine.Framework.Models.Settings.ProjectSettings
  parent: WaveEngine.Framework.Models.Settings
  name: ProjectSettings
  nameWithType: ProjectSettings
  fullName: WaveEngine.Framework.Models.Settings.ProjectSettings
- uid: WaveEngine.Framework.Models.Settings.SceneSettings
  commentId: T:WaveEngine.Framework.Models.Settings.SceneSettings
  parent: WaveEngine.Framework.Models.Settings
  name: SceneSettings
  nameWithType: SceneSettings
  fullName: WaveEngine.Framework.Models.Settings.SceneSettings
- uid: WaveEngine.Framework.Models.Settings.ASettings
  commentId: T:WaveEngine.Framework.Models.Settings.ASettings
  parent: WaveEngine.Framework.Models.Settings
  name: ASettings
  nameWithType: ASettings
  fullName: WaveEngine.Framework.Models.Settings.ASettings
- uid: WaveEngine.Framework.Models.Settings
  commentId: N:WaveEngine.Framework.Models.Settings
  name: WaveEngine.Framework.Models.Settings
  nameWithType: WaveEngine.Framework.Models.Settings
  fullName: WaveEngine.Framework.Models.Settings
