### YamlMime:ManagedReference
items:
- uid: WaveEngine.Framework.Models.Settings.Categories
  commentId: N:WaveEngine.Framework.Models.Settings.Categories
  id: WaveEngine.Framework.Models.Settings.Categories
  children:
  - WaveEngine.Framework.Models.Settings.Categories.OptimizationsData
  - WaveEngine.Framework.Models.Settings.Categories.PhysicCategory
  - WaveEngine.Framework.Models.Settings.Categories.PlatformData
  - WaveEngine.Framework.Models.Settings.Categories.ProfilesData
  - WaveEngine.Framework.Models.Settings.Categories.RenderLayerData
  - WaveEngine.Framework.Models.Settings.Categories.SceneRenderLayerData
  - WaveEngine.Framework.Models.Settings.Categories.ServicesData
  - WaveEngine.Framework.Models.Settings.Categories.ViewportCategory
  langs:
  - csharp
  - vb
  name: WaveEngine.Framework.Models.Settings.Categories
  nameWithType: WaveEngine.Framework.Models.Settings.Categories
  fullName: WaveEngine.Framework.Models.Settings.Categories
  type: Namespace
  assemblies:
  - WaveEngine.Framework
references:
- uid: WaveEngine.Framework.Models.Settings.Categories.OptimizationsData
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.OptimizationsData
  name: OptimizationsData
  nameWithType: OptimizationsData
  fullName: WaveEngine.Framework.Models.Settings.Categories.OptimizationsData
- uid: WaveEngine.Framework.Models.Settings.Categories.SceneRenderLayerData
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.SceneRenderLayerData
  name: SceneRenderLayerData
  nameWithType: SceneRenderLayerData
  fullName: WaveEngine.Framework.Models.Settings.Categories.SceneRenderLayerData
- uid: WaveEngine.Framework.Models.Settings.Categories.RenderLayerData
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.RenderLayerData
  name: RenderLayerData
  nameWithType: RenderLayerData
  fullName: WaveEngine.Framework.Models.Settings.Categories.RenderLayerData
- uid: WaveEngine.Framework.Models.Settings.Categories.PhysicCategory
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.PhysicCategory
  name: PhysicCategory
  nameWithType: PhysicCategory
  fullName: WaveEngine.Framework.Models.Settings.Categories.PhysicCategory
- uid: WaveEngine.Framework.Models.Settings.Categories.PlatformData
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.PlatformData
  name: PlatformData
  nameWithType: PlatformData
  fullName: WaveEngine.Framework.Models.Settings.Categories.PlatformData
- uid: WaveEngine.Framework.Models.Settings.Categories.ProfilesData
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.ProfilesData
  name: ProfilesData
  nameWithType: ProfilesData
  fullName: WaveEngine.Framework.Models.Settings.Categories.ProfilesData
- uid: WaveEngine.Framework.Models.Settings.Categories.ServicesData
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.ServicesData
  name: ServicesData
  nameWithType: ServicesData
  fullName: WaveEngine.Framework.Models.Settings.Categories.ServicesData
- uid: WaveEngine.Framework.Models.Settings.Categories.ViewportCategory
  commentId: T:WaveEngine.Framework.Models.Settings.Categories.ViewportCategory
  name: ViewportCategory
  nameWithType: ViewportCategory
  fullName: WaveEngine.Framework.Models.Settings.Categories.ViewportCategory
